### ISSUE TITLE
Problem with EpipolarSparseMatching

### ISSUE THREAD

**Issue by DieProgrammIDE** [CNES/cars#9] opened 2021-12-31 12:18 UTC
Hello, i am trying to run the Prepare-Step with WorldView-3 Imagery for a City (Potsdam) using 2 Images.

I have created the .geom-Files needed for this Application, downloaded from SRTM and created a config file.

Unfortunately i get these Errors after 1/2 Hour of Matching.

I am providing my Config-Files and the .geom-Files. If needed i can send the Dataset privately.
I have already tried leaving out the Color-Image because it is 8-Band but it doesn't change anything about the Error.

`Performing matching ...: 100%|██████████| 3584/3584 [31:33<00:00,  1.89it/s] 
21-12-30 22:30:29 :: ERROR :: Insufficient amount of matches found (< 100), can not safely estimate epipolar error correction and disparity range
2021-12-30 22:12:56 (WARNING) EpipolarSparseMatching: Warning: tile ignored because of the following error 
itk::ExceptionObject (0x7f0814f48be0)
Location: "unknown" 
File: /usr/include/ITK-4.13/itkEuclideanDistanceMetric.hxx
Line: 64
Description: itk::ERROR: EuclideanDistanceMetric(0x7f0814f3a9f0): The two measurement vectors have unequal size (128 and 351364768)
`
[cars.zip](https://github.com/CNES/cars/files/7796183/cars.zip)

Thank you in advance for your help!

**Comment by duboise-cnes** [comment] 2022-01-03 10:06
Hello @DieProgrammIDE , 
Thanks for using CARS and to have issued your test. 
Your configuration seems adapted. 
Some remarks: 
- Are the two images in sensor geometry ? How did you get your .geom (geometrical model) ? The images and models are read by OTB behind the scene, so you could try to make a ROI with OTB (https://www.orfeo-toolbox.org/CookBook/Applications/app_ExtractROI.html) before to be sure to have readable input data for cars. Please describe how you produce your inputs, especially the geometric model.
- What is the size of input images ? If there are too small, the first prepare sparse matching will not have enough sift matchings (<100) to finalize the preparation step. As said by "Insufficient amount of matches found (< 100), can not safely estimate epipolar error correction and disparity range". 
- "/itkEuclideanDistanceMetric.hxx Line: 64 Description: itk::ERROR: EuclideanDistanceMetric(0x7f0814f3a9f0): The two measurement vectors have unequal size (128 and 351364768) " : the message is misleading and we must fix it but it should not block the prepare step. 
- As you said, You don't need the color image to test, the panchro img1 will be taken in the pipeline. 
Please send your data to cars@cnes.fr . We will try to look at your case and reproduce the potential bug when/if possible. 
Cordially 
Emmanuel

**Comment by duboise-cnes** [comment] 2022-03-29 08:11
Without further answer, I close this december issue, please reopen if the problem is still present

**Closed by duboise-cnes** 2022-03-29 08:11 UTC
