### ISSUE TITLE
21-10-25 04:15:04 :: ERROR :: File /data/input.json does not exist

### ISSUE THREAD

**Issue by Wsdnuaa** [CNES/cars#8] opened 2021-10-25 04:21 UTC
I am sure that my filename is right ,and I use CARS with docker on windows11.However , whatever I used "\\","/"or"\\\\",it could not work .
My cmd line is 
"docker run -v E:/CARStest:/data cnes/cars prepare -i /data/input.json -o /data/outprepare"
This is my TEST data:
![image](https://user-images.githubusercontent.com/41645904/138633968-91b17257-02b9-4a80-93cd-37b71ee19969.png)
and this is my json.
{
    "img1" : " GF7_DLC_E113.6_N34.4_20210117_L1A0000307552-BWDPAN.tiff",
    "color1" : "GF7_DLC_E113.6_N34.4_20210117_L1A0000307552-BWDMUX.tiff",
    "img2" : "GF7_DLC_E113.6_N34.4_20210117_L1A0000307552-FWDPAN.tiff",
    "srtm_dir" : "srtm",
    "nodata1": 0,
    "nodata2": 0
}
and I checked that the imgs completely covered by this srtm dem block.

**Comment by dyoussef** [comment] 2021-11-03 09:31
Please could you send us your data ?

**Comment by duboise-cnes** [comment] 2022-03-29 08:11
Without further answer, I close this december issue, please reopen if the problem is still present

**Closed by duboise-cnes** 2022-03-29 08:11 UTC
