### ISSUE TITLE
cars prepare ending the image matching with an error : free() : invalid size

### ISSUE THREAD

**Issue by atruffiercls** [CNES/cars#10] opened 2022-01-24 09:36 UTC
Hello, 

I am trying to create a DSM with CARS. I succeeded many times in doing so, but this time, I don't know why, at the end of the first step (cars prepare), after the matching step, I get ther error : 

n 'more' : free(): invalid size : 0x00000000011151b0 ***
ktrace: =========

=> 

![cars_issue](https://user-images.githubusercontent.com/98313690/150757037-1ea86eaf-8f41-4ec0-ba90-043a37e11a40.PNG)

Have you ever met this error ? 

The tri-stéréo images I am using are SPOT6 images, which are stored on the CNES cluster.  
The area under study is the Sulawesi region in Indonesia.

Thank you very much for your help. 

Regards, 

Amaury Truffier 
CLS Group

**Comment by duboise-cnes** [comment] 2022-01-24 18:12
Hello @atruffiercls , 
Thanks for the test of CARS. 

This error is new but it seems that the memory is not enough to launch the SPOT6 case. You could monitor your RAM consumption and also try with a ROI of the image to limit the memory. 

It seems more a performance problem than a bug but actually CARS should be more user friendly on exit. 

We can try to exchange internally on CNES cluster to share the data and check your configuration. 

Don't hesitate to contact us. 
cars@cnes.fr

**Comment by duboise-cnes** [comment] 2022-03-29 08:10
Without further answer, I close this january issue, please reopen if the problem is still present

**Closed by duboise-cnes** 2022-03-29 08:10 UTC
